# Generated by Django 3.2.9 on 2021-11-22 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lcompany', models.CharField(max_length=30)),
                ('lprocessor', models.CharField(max_length=30)),
                ('lram', models.IntegerField()),
                ('lprice', models.FloatField()),
                ('del_status', models.CharField(choices=[('Pending', 'Pending'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered')], max_length=30)),
                ('purchasedate', models.DateField()),
            ],
        ),
    ]
