# Generated by Django 3.2.9 on 2021-11-22 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='laptop',
            old_name='lcompany',
            new_name='Company',
        ),
        migrations.RenameField(
            model_name='laptop',
            old_name='del_status',
            new_name='Del_status',
        ),
        migrations.RenameField(
            model_name='laptop',
            old_name='lprice',
            new_name='Price',
        ),
        migrations.RenameField(
            model_name='laptop',
            old_name='lprocessor',
            new_name='Processor',
        ),
        migrations.RenameField(
            model_name='laptop',
            old_name='purchasedate',
            new_name='Purchasedate',
        ),
        migrations.RenameField(
            model_name='laptop',
            old_name='lram',
            new_name='Ram',
        ),
    ]
